### ISSUE TITLE
chapter-04-02 示例报错

### ISSUE THREAD

**Issue by danielmlc** [chenshenhai/rollupjs-note#2]
你好，你的VUE编译的例子跑起来报错
node_modules\_vue@2.5.21@vue\dist\vue.runtime.esm.js (4382:18)
4380:   var options = {
4381:     _isComponent: true,
4382:     _parentVnode: vnode,
                        ^
4383:     parent: parent
4384:   };

**Comment by chenshenhai** [comment]
@danielmlc 感谢你的指正，已经修复好了
