### ISSUE TITLE
第二章chapter02 第一篇文章

### ISSUE THREAD

**Issue by fangyinghua** [chenshenhai/rollupjs-note#5]
demo的地址写错了 
还有npm模块的安装项  跟你项目地址有的不一样 
后面的文章 这些部分都是复制的吧

**Comment by chenshenhai** [comment]
@fangyinghua 您好，部分`npm i`的文档都是一致的，所在在编写的时候有一些一致的内容是直接复制前面的文档哈

**Comment by fangyinghua** [comment]
@chenshenhai  好的 知道了 刚学这个东西 参考参考你写的
